name: pv-simple
channels:
  - conda-forge
dependencies:
  - pyvista
  - trame
  - trame-vtk
  - trame-vuetify
  - jupyter-server-proxy
  - trame-jupyter-extension
  - pip
  - pip:
      - jupyter-server-user-token
